name: CI_NAME

on: push

jobs:
  Pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: self test action
      uses: ./
  Test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache-dependency-path: subdir/package.json
      - run: npm install -g npm@latest
      - run: npm cache clean --force
      - run: npm rm -rf node_modules && rm package-lock.json
      - run: npm install
      - run: npm install karma-mocha-reporter --save-dev
      - run: npm run test-ci
  Super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Super-Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

