name: CI_NAME

on: push

jobs:
  Test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache-dependency-path: subdir/package.json

      - run: npm install -g npm@latest
      - run: npm cache clean --force
      - run: npm rm -rf node_modules && rm package-lock.json
      - run: npm install
      - run: npm install karma --save-dev
      - run: npm install --save-dev jasmine
      - run: npx jasmine init
      - run: npm i karma-teamcity-reporter
      - run: npm i grunt-karma
      - run: npm install karma-jasmine --save-dev
      - run: npm install grunt-karma --save-dev
      - run: npm run test-ci


