name: CI_NAME

on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: |
        npm install
        npm install karma-opera-launcher --save-dev
        ng build
        npm run test-ci
