name: CI_NAME

on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: |
        npm install -g npm@latest
        npm cache clean --force
        npm rm -rf node_modules && rm package-lock.json
        npm install
        nnpm run test

