name: CI_NAME

on: push

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - run: npm install -g npm@latest
      - run: npm cache clean --force
      - run: npm rm -rf node_modules && rm package-lock.json
      - run: npm install
      - run: npm install --save-dev jasmine
      - run: npx jasmine init
      - run: ng test --no-watch --no-progress


